// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrQh3n5sYYeK6RaVdgacx8QGcEbVf7P1I',
    appId: '1:43257582935:web:49e393d0fa7f0cd51a1a12',
    messagingSenderId: '43257582935',
    projectId: 'movie-app-83686',
    authDomain: 'movie-app-83686.firebaseapp.com',
    storageBucket: 'movie-app-83686.appspot.com',
    measurementId: 'G-MEL2ET037X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEim98DshjxpT5_KmhpbIDzEpExFL-ink',
    appId: '1:43257582935:android:91fb29acc57fa0bf1a1a12',
    messagingSenderId: '43257582935',
    projectId: 'movie-app-83686',
    storageBucket: 'movie-app-83686.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6C6CoO0ywRtCaMFeZmS73QmQ1dHHhTCc',
    appId: '1:43257582935:ios:525bbf83e27a59521a1a12',
    messagingSenderId: '43257582935',
    projectId: 'movie-app-83686',
    storageBucket: 'movie-app-83686.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6C6CoO0ywRtCaMFeZmS73QmQ1dHHhTCc',
    appId: '1:43257582935:ios:1a389ea1917188391a1a12',
    messagingSenderId: '43257582935',
    projectId: 'movie-app-83686',
    storageBucket: 'movie-app-83686.appspot.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
